name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building RedSol Android App
      run: docker build . --file Dockerfile --tag redsol-android:$(date +%s)
